Disable class name cop
Negotiatus/rubocop-rulez pull request #1
Opened 2019-09-03 21:20 UTC by timothyfstephens

AirBnb makes an argument that `"User"` is preferable to `User.name`, due to potentially long autoloading chains.

_However_, I feel that the opposite should be encouraged, for several reasons:
- During a refactor, `"User"` could easily get lost, resulting in broken data chains, where `User.name` will raise syntax errors
- Their argument is based on `belongs_to :user, class_name: "User"`, which is a bad example, and in practice, we don't use this in enough places to be substantially at risk for a long loading chain
- We _actively_ made the decision (pre-Rubocop) to do it the `.name` way for the first reason

2019-09-09 15:12 UTC, tjaklitsch approved these changes
fine with this 👍

2019-09-09 20:10 UTC, efmcuiti approved these changes

2019-09-10 14:36 UTC, huywhomustnotbenamed approved these changes

2019-09-10 15:14 UTC, MartinHarding approved these changes

2019-09-10 17:57 UTC, danielfahy requested changes
@timothyfstephens I didn't really appreciate the value of adding 
`User.name` vs `User` until you explained it in the ticket. 
I agree this is actually better than the AirBnB version which enforces something we don't want.

That said however, we should not be turning off a rule, that can automatically perform the effort of actually standardizing without something in it's place.

I did some quick research and found this cop which can automatically enforce this `Model.name` Rails standard for us
https://docs.rubocop.org/projects/rails/en/stable/cops_rails/#railsreflectionclassname

As per the style change docs https://negotiatus.slack.com/archives/G5PLNF1FA/p1560971312138600

Can you enable `Rails/ReflectionClassName` in the rubocop file 

and give an example of the change the cop was able to make automatically for us ?

Just code snippet on the PR will suffice 

Would be really happy to have this guy doing all the work of migrating these for us as we progress around the models over time

2020-01-15 16:58 UTC, closed without merging